# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('body', tinymce.models.HTMLField()),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Newsletter')),
            ],
        ),
    ]
