# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup.Message'),
        ),
    ]
