# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_submission_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='subscription',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='user',
            field=models.ManyToManyField(through='signup.Subscription', to='signup.SignUp'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(choices=[(True, b'Yes'), (False, b'No')], default=1),
        ),
    ]
